spring.application.name=workout-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/meinedb
spring.datasource.username=postgres
spring.datasource.password=passwort
spring.jpa.hibernate.ddl-auto=update
app.cors.origins=http://localhost:5173,http://192.168.178.37:5173